# 90% AI generated
# 10% Bug fixing

version: "3.9"

networks:
  studybuddy:
    driver: bridge

volumes:
  backend_node_modules:
  frontend_node_modules:

services:
  js-backend:
    build:
      context: "./code/Study buddy/backend"
      dockerfile: Dockerfile
    container_name: js-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "./code/Study buddy/backend:/app"
      - "backend_node_modules:/app/node_modules"
    working_dir: /app
    command: npm start
    networks:
      - studybuddy

  js-frontend:
    build:
      context: "./code/Study buddy/frontend"
      dockerfile: Dockerfile
    container_name: js-frontend
    restart: unless-stopped
    init: true
    stdin_open: true
    tty: true
    ports:
      - "8081:8081"   # Metro bundler
      - "19000:19000" # Expo dev server
      - "19001:19001" # Metro WS
      - "19002:19002" # Expo DevTools
      - "19006:19006" # Expo Web
    environment:
      CI: "1"  # replaces --non-interactive
      EXPO_DEVTOOLS_LISTEN_ADDRESS: "0.0.0.0"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      HOME: "/app"
      EXPO_START_TUNNEL: ""   # optional; avoids warning if unset
    volumes:
      - "./code/Study buddy/frontend:/app"
      - "frontend_node_modules:/app/node_modules"
    working_dir: /app
    # Use a valid host mode for Expo CLI
    command: npx expo start --dev-client --web --host lan
    depends_on:
      - js-backend
    networks:
      - studybuddy
